import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Load the font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Set up metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="font-sans antialiased bg-gray-50 text-gray-900">
        {children}</body>
    </html>
  );
}